// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxP3UtXUQh0yp_mkUmJ5bQ0bmUb-09bcM',
    appId: '1:1039234762586:web:d7cda5eb714b3b95afd563',
    messagingSenderId: '1039234762586',
    projectId: 'todo-f44d8',
    authDomain: 'todo-f44d8.firebaseapp.com',
    storageBucket: 'todo-f44d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqQCm8XgJFBo6n0JU7bjzT_Q8cTyTV_PI',
    appId: '1:1039234762586:android:f24bbe0d8cdb383bafd563',
    messagingSenderId: '1039234762586',
    projectId: 'todo-f44d8',
    storageBucket: 'todo-f44d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE8hhKmEkkPzI4a9fc3OD-zw2YB1skuB0',
    appId: '1:1039234762586:ios:94337219a8b75b8cafd563',
    messagingSenderId: '1039234762586',
    projectId: 'todo-f44d8',
    storageBucket: 'todo-f44d8.appspot.com',
    iosBundleId: 'com.jerondev.com.todoCleanArchitectureTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE8hhKmEkkPzI4a9fc3OD-zw2YB1skuB0',
    appId: '1:1039234762586:ios:ffd7b9ecf3c1ba3dafd563',
    messagingSenderId: '1039234762586',
    projectId: 'todo-f44d8',
    storageBucket: 'todo-f44d8.appspot.com',
    iosBundleId: 'com.jerondev.com.todoCleanArchitectureTutorial.RunnerTests',
  );
}
